version: "3.8"
volumes:
  database-data:
    name: "database-data"
services:
  database:
    image: nexo.io/database:0.0.0
    build:
      context: .
      dockerfile: dockerfiles/database/Dockerfile
      args:
        - TIME_ZONE=Europe/Sofia
    environment:
      - POSTGRES_USER=nexo
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nexodb
    volumes:
      - "database-data:/var/lib/postgresql/data"
    container_name: database
    hostname: database
    restart: always
  hello-world:
    image: nexo.io/hello-world:0.0.0
    build:
      context: .
      dockerfile: dockerfiles/hello-world/Dockerfile
      args:
        - TIME_ZONE=Europe/Sofia
    container_name: hello-world
    hostname: hello-world
    ports:
      - "80:80"
    restart: always
    depends_on:
      database:
        condition: service_healthy