version: "3.8"
services:
  hello-world:
    image: nexo.io/hello-world:1.0.0
    build:
      context: .
      dockerfile: dockerfiles/hello-world/Dockerfile  
    container_name: hello-world
    hostname: hello-world
    ports:
      - "80:80"
    restart: unless-stopped