name: Build and Push Docker Images

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Start docker-compose
      run: docker-compose up -d

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_TOKEN }}

    - name: Build and Tag Docker images
      if: startsWith(github.ref, 'refs/tags/')
      env:
        TAG_NAME: ${{ github.ref }}
      run: |
        docker tag nexo.io/hello-world:0.0.0 ne7work/nexo.io:hello-world-${TAG_NAME}
        docker push ne7work/nexo.io:hello-world-${TAG_NAME}

    - name: Stop docker-compose and clean-up
      run: |
        docker-compose down
        docker rmi -f nexo.io/hello-world:0.0.0 
